apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: pvs-teko10 # Replace with your namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
          ports:
            - containerPort: 6379
